name = "ImplicitPlots"
uuid = "55ecb840-b828-11e9-1645-43f4a9f9ace7"
authors = ["Sascha Timme <sascha@timme.xyz>"]
version = "0.1.3"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticPolynomials = "62e018b1-6e46-5407-a5a7-97d4fbcae734"

[compat]
Contour = "^0.5"
DynamicPolynomials = "^0.3.7"
MultivariatePolynomials = "^0.3.6"
RecipesBase = "1"
Requires = "1"
StaticArrays = "^0.12"
StaticPolynomials = "^1.3.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"

[targets]
test = ["Test", "Plots", "DynamicPolynomials", "HomotopyContinuation"]
